apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-container-deployment
  labels:
    app: chat-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-container
  template:
    metadata:
      labels:
        app: chat-container
    spec:
      containers:
      - name: chat-container
        image: <your-dockerhub-username>/chat-container:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: db-storage
          mountPath: /app/users.db
          subPath: users.db
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chat-container-service
spec:
  selector:
    app: chat-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db-storage  # 節點上的實際路徑
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
